// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk8lVnX69DPe-2r5hRyv5ss3DBrRr7W8Q',
    appId: '1:404469091150:web:1b8a97a230c98a34edec1f',
    messagingSenderId: '404469091150',
    projectId: 'collegeproject-9246d',
    authDomain: 'collegeproject-9246d.firebaseapp.com',
    storageBucket: 'collegeproject-9246d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiqeejqXX-VTCffd0J4h9DotWo7hXmLC0',
    appId: '1:404469091150:android:bf0c5b96b409a7c5edec1f',
    messagingSenderId: '404469091150',
    projectId: 'collegeproject-9246d',
    storageBucket: 'collegeproject-9246d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKoeFYO_CDcBzonFZ6kxbFJ1VSzlkE7O0',
    appId: '1:404469091150:ios:397bc83322776856edec1f',
    messagingSenderId: '404469091150',
    projectId: 'collegeproject-9246d',
    storageBucket: 'collegeproject-9246d.appspot.com',
    iosBundleId: 'com.example.baranwalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKoeFYO_CDcBzonFZ6kxbFJ1VSzlkE7O0',
    appId: '1:404469091150:ios:6593def282aa5ed2edec1f',
    messagingSenderId: '404469091150',
    projectId: 'collegeproject-9246d',
    storageBucket: 'collegeproject-9246d.appspot.com',
    iosBundleId: 'com.example.baranwalProject.RunnerTests',
  );
}
